packages: []
catalogs:
  browser:
    puppeteer-core: ^24.25.0
    puppeteer-screen-recorder: ^3.0.6
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.3.1
    pncat: ^0.7.0
    taze: ^19.7.0
  ffmpeg:
    '@ffmpeg-installer/ffmpeg': ^1.1.0
  lint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.37.0
    lint-staged: ^16.2.4
    simple-git-hooks: ^2.13.1
  network:
    ws: ^8.18.3
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.2.0
    cac: ^6.7.14
    execa: ^9.6.0
    pathe: ^2.0.3
    rimraf: ^6.0.1
    unconfig: ^7.3.3
  script:
    tsx: ^4.20.6
  terminal:
    '@xterm/addon-serialize': ^0.13.0
    '@xterm/headless': ^5.5.0
  test:
    vitest: ^3.2.4
  tsc:
    typescript: ^5.9.3
  types:
    '@types/kill-port': ^2.0.3
    '@types/node': ^24.8.0
    '@types/ws': ^8.18.1
  utils:
    ansi_up: ^6.0.6
    get-port: ^7.1.0
    kill-port: 1.6.1
    restore-cursor: ^5.1.0
    string-width: ^8.1.0
    strip-ansi: ^7.1.2
