packages: []
catalogs:
  browser:
    puppeteer-core: ^24.22.3
    puppeteer-screen-recorder: ^3.0.6
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.2.3
    pncat: ^0.5.4
    taze: ^19.7.0
  ffmpeg:
    '@ffmpeg-installer/ffmpeg': ^1.1.0
  lint:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.36.0
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
  network:
    ws: ^8.18.3
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.2.0
    cac: ^6.7.14
    execa: ^9.6.0
    pathe: ^2.0.3
    rimraf: ^6.0.1
    unconfig: ^7.3.3
  script:
    tsx: ^4.20.6
  terminal:
    '@xterm/addon-serialize': ^0.13.0
    '@xterm/headless': ^5.5.0
  test:
    vitest: ^3.2.4
  tsc:
    typescript: ^5.9.2
  types:
    '@types/kill-port': ^2.0.3
    '@types/node': ^24.6.0
    '@types/ws': ^8.18.1
  utils:
    fancy-ansi: ^0.1.3
    get-port: ^7.1.0
    kill-port: 1.6.1
    string-width: ^8.1.0
