packages: []
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.2.3
    pncat: ^0.5.1
    taze: ^19.3.0
  dev:
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
  network:
    ws: ^8.18.3
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.1.0
    cac: ^6.7.14
    execa: ^9.6.0
    pathe: ^2.0.3
    unconfig: ^7.3.3
  screeshot:
    puppeteer-core: ^24.17.1
  script:
    tsx: ^4.20.5
  test:
    vitest: ^3.2.4
  types:
    '@types/kill-port': ^2.0.3
    '@types/node': ^24.3.0
    '@types/ws': ^8.18.1
  utils:
    fancy-ansi: ^0.1.3
    get-port: ^7.1.0
    kill-port: 1.6.1
    string-width: ^8.0.0
  xterm:
    '@xterm/addon-serialize': ^0.13.0
    '@xterm/headless': ^5.5.0
