packages: []
catalogs:
  automation:
    puppeteer: ^24.16.0
  build:
    unbuild: ^3.6.0
  cli:
    bumpp: ^10.2.2
    czg: ^1.12.0
    pncat: ^0.4.1
    taze: ^19.1.0
  dev:
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.2.0
    eslint: ^9.32.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
  network:
    ws: ^8.18.3
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.1.0
    cac: ^6.7.14
    execa: ^9.6.0
    pathe: ^2.0.3
    unconfig: ^7.3.2
  script:
    tsx: ^4.20.3
  test:
    vitest: ^3.2.4
  types:
    '@types/kill-port': ^2.0.3
    '@types/node': ^24.2.0
    '@types/puppeteer': ^7.0.4
    '@types/ws': ^8.18.1
  utils:
    emoji-regex: ^10.4.0
    get-port: ^7.1.0
    kill-port: 1.6.1
    strip-ansi: ^7.1.0
